version: '3.1'
services:
  cassandraNode1:
    image: cassandra
    volumes:
      - ./scripts/tables.cql:/tables.cql
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandraNode1,cassandraNode2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=50M
  cassandraNode2:
    image: cassandra
    ports:
      - 9043:9042
    environment:
      - CASSANDRA_SEEDS=cassandraNode1,cassandraNode2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=50M