spring:
  data:
    cassandra:
      contact-points: cassandraNode1,cassandraNode2
      keyspacename: employeeKeySpace
      ports:
        - 9043:9042
      entity-base-package: com.nosql.springboot.cassandara.domain.employee
