#spring:
#  data:
#    cassandra:
#      port: 9042
#      contact-points: mycassandra
#      keyspace-name: mykeyspace
#      entity-base-package: com.nosql.springboot.cassandara.domain.employee

spring:
  data:
    cassandra:
      contact-points: mycassandra,cassandra2
      keyspacename: employeeKeySpace
      ports:
        - 9043:9042
      entity-base-package: com.nosql.springboot.cassandara.domain.employee